### ISSUE TITLE
iPhone source code

### ISSUE THREAD

**Issue by macroday** [ndew623/AndroidCrypt#7]
Do you have any iPhone source code?

**Comment by ndew623** [comment]
AndroidCrypt is an Android specific project, so there is no iPhone source code. AESCrypt is the open source project that develops the encryption software used by AndroidCrypt.

You can find source code for AESCrypt here: https://www.aescrypt.com/
You can find an iPhone app that also uses AESCrypt here: https://itunes.apple.com/us/app/aescrypt/id791675640
(The developers of the iPhone application do not appear to have made their source code available, but I am not affiliated with them. You will have to contact them directly if you are interested in their source code.)
